import { useState, useEffect, useCallback } from 'react';
import {
  Trophy, ThumbsUp, TrendingUp, AlertTriangle,
  Eye, Bell, Shuffle, Clock, Timer, Target,
  Download, Trash2, ChevronDown, ChevronUp,
  FileText, FileJson, Inbox, Globe, Monitor,
  CalendarDays, Zap, ArrowRight,
} from 'lucide-react';
import { getSessions, deleteSession, clearAllSessions } from '../services/sessionStore';

// ─── palette ──────────────────────────────────────────────────────────────────
const C = {
  bg:        '#000',
  surface:   '#0f0f0f',
  raised:    '#1a1a1a',
  border:    '#2a2a2a',
  borderHi:  '#fff',
  text:      '#fff',
  muted:     '#888',
  faint:     '#444',
  // semantic — kept minimal, only for meaning
  good:      '#fff',
  warn:      '#aaa',
  danger:    '#fff',
};

// grade uses white shades so it stays monochrome but still distinct
const gradeStyle = (g) => ({
  Excellent:         { color: '#fff',  border: '#fff' },
  Good:              { color: '#ccc',  border: '#ccc' },
  Fair:              { color: '#999',  border: '#999' },
  'Needs Improvement': { color: '#666', border: '#666' },
}[g] || { color: '#fff', border: '#fff' });

const GradeIcon = ({ grade, size = 18 }) => {
  const c = gradeStyle(grade).color;
  if (grade === 'Excellent') return <Trophy        size={size} color={c} />;
  if (grade === 'Good')      return <ThumbsUp      size={size} color={c} />;
  if (grade === 'Fair')      return <TrendingUp    size={size} color={c} />;
  return                            <AlertTriangle size={size} color={c} />;
};

const elapsed = (ms) => {
  if (!ms || ms <= 0) return '0s';
  const s = Math.floor(ms / 1000), m = Math.floor(s / 60), h = Math.floor(m / 60);
  if (h > 0) return `${h}h ${m % 60}m`;
  if (m > 0) return `${m}m ${s % 60}s`;
  return `${s}s`;
};

const fmtDate = (iso) =>
  iso ? new Date(iso).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' }) : '—';
const fmtDateShort = (iso) =>
  iso ? new Date(iso).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : '—';

const sessionSummary = (s) => {
  const pct = s.attentionPercent;
  const focus = pct >= 85 ? 'really locked in' : pct >= 65 ? 'mostly focused' : pct >= 40 ? 'a bit distracted' : 'quite distracted';
  const d = s.tabSwitches === 0 ? 'with zero distractions' : s.tabSwitches === 1 ? 'with 1 distraction' : `with ${s.tabSwitches} distractions`;
  return `You were ${focus} during this ${s.totalDuration} session, ${d}.`;
};

// ─── downloads ────────────────────────────────────────────────────────────────
function buildTextReport(s) {
  const div = '─'.repeat(60);
  const line = (l, v) => `  ${l.padEnd(22)}: ${v}`;
  const log = (s.awayEvents || []).length === 0
    ? '  No distractions recorded.'
    : (s.awayEvents || []).map((ev, i) =>
        `  ${String(i+1).padStart(2)}. [${ev.kind === 'tab' ? 'Tab Switch ' : 'App/Minimize'}]  ` +
        `Left: ${ev.startTime ? new Date(ev.startTime).toLocaleTimeString() : '?'}  ` +
        `Returned: ${ev.endTime ? new Date(ev.endTime).toLocaleTimeString() : '—'}  ` +
        `Duration: ${ev.durationMs ? elapsed(ev.durationMs) : '—'}  | ${ev.label}`
      ).join('\n');
  return [
    `ZENITH — SESSION REPORT`, div,
    `  Date       : ${s.date || fmtDateShort(s.startTimeISO)}`,
    `  Session ID : ${s.id}`, div, `SUMMARY`,
    line('Start Time', s.startTime), line('End Time', s.endTime),
    line('Total Duration', s.totalDuration), line('Focused Time', s.focusedTime),
    line('Away Time', s.awayTime), line('Attention Score', `${s.attentionPercent}%`),
    line('Grade', s.grade), line('No-Face Alerts', s.noFaceAlerts), line('Distractions', s.tabSwitches),
    div, `DISTRACTION LOG`, log, div,
    `Generated by Zenith on ${new Date().toLocaleString()}`,
  ].join('\n');
}

const dl = (blob, name) => {
  const url = URL.createObjectURL(blob), a = document.createElement('a');
  a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url);
};
const downloadText    = (s) => dl(new Blob([buildTextReport(s)], { type: 'text/plain' }), `zenith-session-${s.id}.txt`);
const downloadJSON    = (s) => dl(new Blob([JSON.stringify(s, null, 2)], { type: 'application/json' }), `zenith-session-${s.id}.json`);
const downloadAllCSV  = (sessions) => {
  const h = ['ID','Date','Start','End','Total Duration','Focused Time','Away Time','Attention %','Grade','Alerts','Distractions'];
  const rows = sessions.map(s =>
    [s.id, s.date || fmtDateShort(s.startTimeISO), s.startTime, s.endTime,
     s.totalDuration, s.focusedTime, s.awayTime, s.attentionPercent, s.grade, s.noFaceAlerts, s.tabSwitches]
    .map(v => `"${v}"`).join(','));
  dl(new Blob([[h.join(','), ...rows].join('\n')], { type: 'text/csv' }), 'zenith-all-sessions.csv');
};

// ─── main ─────────────────────────────────────────────────────────────────────
export default function AppTracker() {
  const [sessions, setSessions]         = useState([]);
  const [selected, setSelected]         = useState(null);
  const [confirmClear, setConfirmClear] = useState(false);
  const [filter, setFilter]             = useState('all');

  const reload = useCallback(() => setSessions(getSessions()), []);
  useEffect(() => { reload(); }, [reload]);

  const handleDelete   = (id) => { deleteSession(id); if (selected === id) setSelected(null); reload(); };
  const handleClearAll = () => { clearAllSessions(); setSelected(null); setConfirmClear(false); reload(); };

  const filtered = filter === 'all' ? sessions : sessions.filter(s => s.grade === filter);
  const total    = sessions.length;
  const avgAttn  = total === 0 ? 0 : Math.round(sessions.reduce((a, s) => a + (s.attentionPercent || 0), 0) / total);
  const best     = total === 0 ? null : sessions.reduce((a, s) => s.attentionPercent > a.attentionPercent ? s : a, sessions[0]);

  return (
    <div style={S.page}>

      {/* header */}
      <div style={S.pageHeader}>
        <div>
          <h1 style={S.title}>Your Focus History</h1>
          <p style={S.sub}>A look back at how well you've been staying on task.</p>
        </div>
        {total > 0 && (
          <div style={S.headerActions}>
            <Btn icon={<Download size={14} />} label="Export CSV" onClick={() => downloadAllCSV(sessions)} />
            {confirmClear ? (
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <span style={{ color: C.muted, fontSize: '0.88rem' }}>Remove all sessions?</span>
                <Btn label="Yes, remove" onClick={handleClearAll} danger />
                <Btn label="Cancel" onClick={() => setConfirmClear(false)} />
              </div>
            ) : (
              <Btn icon={<Trash2 size={14} />} label="Clear history" onClick={() => setConfirmClear(true)} danger />
            )}
          </div>
        )}
      </div>

      {/* overview strip */}
      {total > 0 && (
        <div style={S.overviewStrip}>
          <OverviewStat num={total}           label="sessions recorded" />
          <div style={S.overviewDivider} />
          <OverviewStat num={`${avgAttn}%`}   label="average attention" dim={avgAttn < 50} />
          <div style={S.overviewDivider} />
          <OverviewStat num={best?.grade ?? '—'} label="best grade achieved" />
        </div>
      )}

      {/* filter tabs */}
      {total > 0 && (
        <div style={S.filterRow}>
          <span style={S.filterLabel}>Show:</span>
          {['all', 'Excellent', 'Good', 'Fair', 'Needs Improvement'].map(f => (
            <button
              key={f}
              style={{ ...S.filterTab, ...(filter === f ? S.filterTabActive : {}) }}
              onClick={() => setFilter(f)}
            >
              {f === 'all' ? 'All sessions' : f}
            </button>
          ))}
        </div>
      )}

      {/* empty */}
      {total === 0 && (
        <div style={S.emptyState}>
          <div style={S.emptyIcon}><Inbox size={32} color={C.faint} /></div>
          <p style={S.emptyTitle}>Nothing here yet</p>
          <p style={S.emptySub}>Head over to Face Detection, run a session, and your report will appear here.</p>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: C.muted, fontSize: '0.88rem', marginTop: '0.75rem' }}>
            <span>Go to Face Detection</span><ArrowRight size={13} />
          </div>
        </div>
      )}

      {/* list */}
      <div style={S.list}>
        {filtered.map((s, idx) => (
          <SessionCard
            key={s.id} session={s} index={total - idx}
            expanded={selected === s.id}
            onToggle={() => setSelected(selected === s.id ? null : s.id)}
            onDelete={() => handleDelete(s.id)}
            onDownloadTxt={() => downloadText(s)}
            onDownloadJSON={() => downloadJSON(s)}
          />
        ))}
        {filtered.length === 0 && total > 0 && (
          <p style={{ color: C.faint, textAlign: 'center', padding: '3rem 0' }}>No sessions with that grade yet.</p>
        )}
      </div>
    </div>
  );
}

// ─── session card ─────────────────────────────────────────────────────────────
function SessionCard({ session: s, index, expanded, onToggle, onDelete, onDownloadTxt, onDownloadJSON }) {
  const gs = gradeStyle(s.grade);

  return (
    <div style={{ ...S.card, ...(expanded ? { borderColor: '#fff' } : {}) }}>

      {/* summary row */}
      <div style={S.cardRow} onClick={onToggle} role="button" tabIndex={0} onKeyDown={e => e.key === 'Enter' && onToggle()}>

        {/* grade badge */}
        <div style={{ ...S.gradeBadge, borderColor: gs.border + '55' }}>
          <GradeIcon grade={s.grade} size={20} />
          <span style={{ color: gs.color, fontWeight: 700, fontSize: '0.75rem', letterSpacing: '0.3px' }}>{s.grade}</span>
        </div>

        {/* info */}
        <div style={S.cardInfo}>
          <div style={S.cardMeta}>
            <CalendarDays size={13} color={C.faint} />
            <span>{fmtDate(s.startTimeISO)}</span>
            <span style={{ marginLeft: 'auto', color: C.faint, fontSize: '0.75rem' }}>#{index}</span>
          </div>
          <p style={S.cardSummary}>{sessionSummary(s)}</p>
        </div>

        {/* quick stats */}
        <div style={S.quickStats}>
          <QStat icon={<Clock   size={12} color={C.faint} />} value={s.totalDuration} />
          <QStat icon={<Eye     size={12} color={C.muted} />} value={`${s.attentionPercent}%`} bright />
          <QStat icon={<Shuffle size={12} color={C.faint} />} value={`${s.tabSwitches} away`} />
        </div>

        <div style={{ color: C.faint, flexShrink: 0 }}>
          {expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </div>
      </div>

      {/* expanded */}
      {expanded && (
        <div style={S.cardDetail}>
          <div style={S.divider} />

          {/* time row */}
          <div style={S.timeRow}>
            <TBlock label="Started"  value={s.startTime} />
            <ArrowRight size={13} color={C.faint} />
            <TBlock label="Ended"    value={s.endTime} />
            <div style={{ width: '1px', height: '28px', backgroundColor: C.border, margin: '0 0.5rem' }} />
            <TBlock label="Duration" value={s.totalDuration} />
          </div>

          {/* stat pills */}
          <div style={S.pillRow}>
            <SPill icon={<Target  size={13} />} label="Focused"      value={s.focusedTime} />
            <SPill icon={<Zap     size={13} />} label="Away"         value={s.awayTime} />
            <SPill icon={<Eye     size={13} />} label="Attention"    value={`${s.attentionPercent}%`} bright />
            <SPill icon={<Bell    size={13} />} label="Alerts"       value={s.noFaceAlerts} />
            <SPill icon={<Shuffle size={13} />} label="Distractions" value={s.tabSwitches} />
          </div>

          {/* attention bar */}
          <div style={{ marginBottom: '1.5rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '6px' }}>
              <span style={{ color: C.muted, fontSize: '0.8rem', letterSpacing: '0.3px', textTransform: 'uppercase' }}>Attention score</span>
              <span style={{ color: '#fff', fontWeight: 700, fontSize: '0.88rem' }}>{s.attentionPercent}%</span>
            </div>
            <div style={S.barTrack}>
              <div style={{ ...S.barFill, width: `${s.attentionPercent}%` }} />
            </div>
          </div>

          {/* distraction log */}
          {(s.awayEvents || []).length > 0 && (
            <div style={{ marginBottom: '1.5rem' }}>
              <p style={S.sectionLabel}>
                <Shuffle size={13} color={C.muted} />
                {s.awayEvents.length === 1 ? 'You left once during this session' : `You left ${s.awayEvents.length} times during this session`}
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                {s.awayEvents.map((ev, i) => (
                  <div key={i} style={S.distractRow}>
                    <div style={{ ...S.kindTag, borderColor: C.border }}>
                      {ev.kind === 'tab' ? <Globe size={11} color={C.muted} /> : <Monitor size={11} color={C.muted} />}
                      <span style={{ color: C.muted, fontSize: '0.75rem', fontWeight: 600 }}>
                        {ev.kind === 'tab' ? 'Tab' : 'App'}
                      </span>
                    </div>
                    <span style={{ color: C.muted, fontSize: '0.82rem', flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {ev.label}
                    </span>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '4px', color: C.faint, fontSize: '0.78rem', flexShrink: 0 }}>
                      <span>{ev.startTime ? new Date(ev.startTime).toLocaleTimeString() : '?'}</span>
                      <ArrowRight size={10} color={C.faint} />
                      <span>{ev.endTime ? new Date(ev.endTime).toLocaleTimeString() : '—'}</span>
                    </div>
                    <span style={{ color: ev.durationMs > 30000 ? '#aaa' : '#fff', fontWeight: 700, fontSize: '0.82rem', flexShrink: 0, minWidth: '40px', textAlign: 'right' }}>
                      {ev.durationMs ? elapsed(ev.durationMs) : '—'}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* actions */}
          <div style={{ display: 'flex', gap: '0.6rem', flexWrap: 'wrap', alignItems: 'center' }}>
            <Btn icon={<FileText size={13} />} label="Download .txt"  onClick={onDownloadTxt} />
            <Btn icon={<FileJson size={13} />} label="Download .json" onClick={onDownloadJSON} />
            <div style={{ marginLeft: 'auto' }}>
              <Btn icon={<Trash2 size={13} />} label="Delete" onClick={onDelete} danger />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── small components ─────────────────────────────────────────────────────────
function Btn({ icon, label, onClick, danger = false }) {
  return (
    <button
      style={{
        display: 'inline-flex', alignItems: 'center', gap: '6px',
        backgroundColor: 'transparent',
        color: danger ? '#888' : '#fff',
        border: `1px solid ${danger ? '#444' : '#333'}`,
        borderRadius: '7px', padding: '7px 13px',
        cursor: 'pointer', fontWeight: 600, fontSize: '0.82rem',
        letterSpacing: '0.2px',
      }}
      onClick={onClick}
    >
      {icon}{label}
    </button>
  );
}

function OverviewStat({ num, label, dim = false }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '3px', padding: '0 2rem' }}>
      <span style={{ fontSize: '2rem', fontWeight: 800, color: dim ? C.muted : '#fff', lineHeight: 1 }}>{num}</span>
      <span style={{ color: C.faint, fontSize: '0.8rem' }}>{label}</span>
    </div>
  );
}

function QStat({ icon, value, bright = false }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '4px', color: bright ? '#fff' : C.muted, fontSize: '0.82rem', fontWeight: bright ? 700 : 500 }}>
      {icon}<span>{value}</span>
    </div>
  );
}

function SPill({ icon, label, value, bright = false }) {
  return (
    <div style={{ backgroundColor: '#111', border: `1px solid ${C.border}`, borderRadius: '8px', padding: '0.55rem 0.85rem', display: 'flex', flexDirection: 'column', gap: '3px', minWidth: '80px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '4px', color: C.faint, fontSize: '0.68rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
        {icon}<span>{label}</span>
      </div>
      <span style={{ color: bright ? '#fff' : C.muted, fontWeight: 700, fontSize: '0.95rem' }}>{value}</span>
    </div>
  );
}

function TBlock({ label, value }) {
  return (
    <div style={{ textAlign: 'center' }}>
      <div style={{ color: C.faint, fontSize: '0.68rem', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '2px' }}>{label}</div>
      <div style={{ color: '#fff', fontWeight: 700, fontSize: '0.92rem' }}>{value}</div>
    </div>
  );
}

// ─── styles ───────────────────────────────────────────────────────────────────
const S = {
  page: {
    padding: '2.5rem 2rem', maxWidth: '900px', margin: '0 auto',
    fontFamily: '"Inter", system-ui, sans-serif', color: '#fff',
    minHeight: '100vh', backgroundColor: C.bg,
  },
  pageHeader: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start',
    flexWrap: 'wrap', gap: '1rem', marginBottom: '2.5rem',
    borderBottom: `1px solid ${C.border}`, paddingBottom: '2rem',
  },
  title: {
    fontSize: '2.2rem', margin: '0 0 0.4rem 0', fontWeight: 800,
    color: '#fff', letterSpacing: '-0.5px',
  },
  sub: { color: C.muted, margin: 0, fontSize: '0.95rem' },
  headerActions: { display: 'flex', gap: '0.6rem', alignItems: 'center', flexWrap: 'wrap' },

  overviewStrip: {
    display: 'flex', alignItems: 'center',
    border: `1px solid ${C.border}`, borderRadius: '12px',
    padding: '1.5rem 0', marginBottom: '2rem', flexWrap: 'wrap',
    backgroundColor: C.surface,
  },
  overviewDivider: { width: '1px', height: '44px', backgroundColor: C.border, flexShrink: 0 },

  filterRow: {
    display: 'flex', alignItems: 'center', gap: '0',
    borderBottom: `1px solid ${C.border}`, marginBottom: '2rem', flexWrap: 'wrap',
  },
  filterLabel: { color: C.faint, fontSize: '0.8rem', marginRight: '0.75rem', paddingBottom: '0.75rem' },
  filterTab: {
    background: 'none', border: 'none', borderBottom: '2px solid transparent',
    color: C.faint, fontSize: '0.88rem', fontWeight: 500,
    padding: '0 1rem 0.75rem', cursor: 'pointer',
  },
  filterTabActive: {
    color: '#fff', fontWeight: 700, borderBottomColor: '#fff',
  },

  emptyState: {
    display: 'flex', flexDirection: 'column', alignItems: 'center',
    padding: '6rem 2rem', textAlign: 'center',
  },
  emptyIcon: {
    width: '68px', height: '68px', borderRadius: '50%',
    border: `1px solid ${C.border}`, backgroundColor: C.surface,
    display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '1.25rem',
  },
  emptyTitle: { color: '#fff', fontWeight: 700, fontSize: '1.1rem', margin: '0 0 0.5rem 0' },
  emptySub:   { color: C.muted, fontSize: '0.9rem', maxWidth: '340px', lineHeight: 1.7, margin: 0 },

  list: { display: 'flex', flexDirection: 'column', gap: '0.6rem' },

  card: {
    backgroundColor: C.surface, borderRadius: '12px',
    border: `1px solid ${C.border}`, overflow: 'hidden',
    transition: 'border-color 0.15s',
  },
  cardRow: {
    display: 'flex', alignItems: 'center', gap: '1rem',
    padding: '1.1rem 1.25rem', cursor: 'pointer', userSelect: 'none', flexWrap: 'wrap',
  },
  gradeBadge: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '5px',
    padding: '0.65rem 0.8rem', borderRadius: '8px', flexShrink: 0, minWidth: '70px',
    border: '1px solid',
    backgroundColor: '#111',
  },
  cardInfo: { flex: 1, minWidth: '180px' },
  cardMeta: {
    display: 'flex', alignItems: 'center', gap: '0.4rem',
    color: C.faint, fontSize: '0.82rem', marginBottom: '0.35rem',
  },
  cardSummary: { color: '#fff', fontSize: '0.92rem', margin: 0, lineHeight: 1.55 },
  quickStats: { display: 'flex', flexDirection: 'column', gap: '5px', flexShrink: 0 },

  cardDetail: { padding: '0 1.25rem 1.25rem' },
  divider: { height: '1px', backgroundColor: C.border, marginBottom: '1.25rem' },

  timeRow: {
    display: 'flex', alignItems: 'center', gap: '0.75rem',
    marginBottom: '1.25rem', flexWrap: 'wrap',
  },
  pillRow: { display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '1.5rem' },

  barTrack: { height: '4px', backgroundColor: C.border, borderRadius: '99px', overflow: 'hidden' },
  barFill:  { height: '100%', borderRadius: '99px', backgroundColor: '#fff', transition: 'width 0.4s ease' },

  sectionLabel: {
    display: 'flex', alignItems: 'center', gap: '0.5rem',
    color: C.muted, fontSize: '0.85rem', margin: '0 0 0.75rem 0',
  },
  distractRow: {
    display: 'flex', alignItems: 'center', gap: '0.75rem',
    backgroundColor: '#111', border: `1px solid ${C.border}`,
    borderRadius: '7px', padding: '0.55rem 0.85rem', flexWrap: 'wrap',
  },
  kindTag: {
    display: 'inline-flex', alignItems: 'center', gap: '4px',
    padding: '2px 8px', borderRadius: '5px', border: '1px solid', flexShrink: 0,
    backgroundColor: '#1a1a1a',
  },
};
