import { useState, useEffect, useCallback } from 'react';
import {
  Trophy, ThumbsUp, TrendingUp, AlertTriangle,
  Eye, Bell, Shuffle, Clock, Timer, Target,
  Download, Trash2, ChevronDown, ChevronUp,
  FileText, FileJson, Inbox, Globe, Monitor,
  CalendarDays, Zap, ArrowRight, Activity, Calendar, History
} from 'lucide-react';
import { getSessions, deleteSession, clearAllSessions } from '../services/sessionStore';
import { useTheme } from "../Theme";

const elapsed = (ms) => {
  if (!ms || ms <= 0) return '0s';
  const s = Math.floor(ms / 1000), m = Math.floor(s / 60), h = Math.floor(m / 60);
  if (h > 0) return `${h}h ${m % 60}m`;
  if (m > 0) return `${m}m ${s % 60}s`;
  return `${s}s`;
};

const fmtDate = (iso) =>
  iso ? new Date(iso).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' }) : '—';
const fmtDateShort = (iso) =>
  iso ? new Date(iso).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : '—';

const sessionSummary = (s) => {
  const pct = s.attentionPercent;
  const focus = pct >= 85 ? 'really locked in' : pct >= 65 ? 'mostly focused' : pct >= 40 ? 'a bit distracted' : 'quite distracted';
  const d = s.tabSwitches === 0 ? 'with zero distractions' : s.tabSwitches === 1 ? 'with 1 distraction' : `with ${s.tabSwitches} distractions`;
  return `You were ${focus} during this ${s.totalDuration} session, ${d}.`;
};

const Noise = () => (
  <svg style={{ position: "fixed", inset: 0, width: "100%", height: "100%", pointerEvents: "none", zIndex: 0, opacity: 0.04 }}>
    <filter id="noise">
      <feTurbulence type="fractalNoise" baseFrequency="0.65" numOctaves="3" stitchTiles="stitch" />
    </filter>
    <rect width="100%" height="100%" filter="url(#noise)" />
  </svg>
);

// ─── downloads ────────────────────────────────────────────────────────────────
function buildTextReport(s) {
  const div = '─'.repeat(60);
  const line = (l, v) => `  ${l.padEnd(22)}: ${v}`;
  const log = (s.awayEvents || []).length === 0
    ? '  No distractions recorded.'
    : (s.awayEvents || []).map((ev, i) =>
        `  ${String(i+1).padStart(2)}. [${ev.kind === 'tab' ? 'Tab Switch ' : 'App/Minimize'}]  ` +
        `Left: ${ev.startTime ? new Date(ev.startTime).toLocaleTimeString() : '?'}  ` +
        `Returned: ${ev.endTime ? new Date(ev.endTime).toLocaleTimeString() : '—'}  ` +
        `Duration: ${ev.durationMs ? elapsed(ev.durationMs) : '—'}  | ${ev.label}`
      ).join('\n');
  return [
    `ZENITH — SESSION REPORT`, div,
    `  Date       : ${s.date || fmtDateShort(s.startTimeISO)}`,
    `  Session ID : ${s.id}`, div, `SUMMARY`,
    line('Start Time', s.startTime), line('End Time', s.endTime),
    line('Total Duration', s.totalDuration), line('Focused Time', s.focusedTime),
    line('Away Time', s.awayTime), line('Attention Score', `${s.attentionPercent}%`),
    line('Grade', s.grade), line('No-Face Alerts', s.noFaceAlerts), line('Distractions', s.tabSwitches),
    div, `DISTRACTION LOG`, log, div,
    `Generated by Zenith on ${new Date().toLocaleString()}`,
  ].join('\n');
}

const dl = (blob, name) => {
  const url = URL.createObjectURL(blob), a = document.createElement('a');
  a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url);
};
const downloadText    = (s) => dl(new Blob([buildTextReport(s)], { type: 'text/plain' }), `zenith-session-${s.id}.txt`);
const downloadJSON    = (s) => dl(new Blob([JSON.stringify(s, null, 2)], { type: 'application/json' }), `zenith-session-${s.id}.json`);
const downloadAllCSV  = (sessions) => {
  const h = ['ID','Date','Start','End','Total Duration','Focused Time','Away Time','Attention %','Grade','Alerts','Distractions'];
  const rows = sessions.map(s =>
    [s.id, s.date || fmtDateShort(s.startTimeISO), s.startTime, s.endTime,
     s.totalDuration, s.focusedTime, s.awayTime, s.attentionPercent, s.grade, s.noFaceAlerts, s.tabSwitches]
    .map(v => `"${v}"`).join(','));
  dl(new Blob([[h.join(','), ...rows].join('\n')], { type: 'text/csv' }), 'zenith-all-sessions.csv');
};

export default function AppTracker() {
  const { dark } = useTheme();
  const [sessions, setSessions] = useState([]);
  const [selected, setSelected] = useState(null);
  const [confirmClear, setConfirmClear] = useState(false);
  const [filter, setFilter] = useState('all');

  const bg = dark ? "#080808" : "#F5F5F0";
  const fg = dark ? "#FFFFFF" : "#0A0A0A";
  const fgMuted = dark ? "rgba(255,255,255,0.45)" : "rgba(0,0,0,0.45)";
  const border = dark ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.08)";
  const cardBg = dark ? "rgba(255,255,255,0.03)" : "rgba(0,0,0,0.02)";
  const cardBorder = dark ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.1)";

  const reload = useCallback(() => setSessions(getSessions()), []);
  useEffect(() => { reload(); }, [reload]);

  const handleDelete = (id) => { deleteSession(id); if (selected === id) setSelected(null); reload(); };
  const handleClearAll = () => { clearAllSessions(); setSelected(null); setConfirmClear(false); reload(); };

  const filtered = filter === 'all' ? sessions : sessions.filter(s => s.grade === filter);
  const total = sessions.length;
  const avgAttn = total === 0 ? 0 : Math.round(sessions.reduce((a, s) => a + (s.attentionPercent || 0), 0) / total);
  const best = total === 0 ? null : sessions.reduce((a, s) => s.attentionPercent > a.attentionPercent ? s : a, sessions[0]);

  useEffect(() => {
    const style = document.createElement("style");
    style.textContent = `
      @import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;1,9..40,300&display=swap');

      .fade-up {
        opacity: 0;
        transform: translateY(20px);
        transition: opacity 0.6s cubic-bezier(0.16,1,0.3,1), transform 0.6s cubic-bezier(0.16,1,0.3,1);
      }
      .fade-up.visible { opacity: 1; transform: translateY(0); }

      .premium-card {
        transition: all 0.4s cubic-bezier(0.16,1,0.3,1);
        position: relative;
        overflow: hidden;
      }
      .premium-card::before {
        content: '';
        position: absolute;
        inset: 0;
        background: radial-gradient(circle at 50% 0%, rgba(255,255,255,0.06) 0%, transparent 60%);
        opacity: 0;
        transition: opacity 0.4s;
      }
      .premium-card:hover::before { opacity: 1; }

      .glow-btn {
        position: relative;
        overflow: hidden;
        transition: all 0.3s ease;
      }
      .glow-btn::after {
        content: '';
        position: absolute;
        inset: 0;
        background: radial-gradient(circle at center, rgba(255,255,255,0.15) 0%, transparent 70%);
        opacity: 0;
        transition: opacity 0.3s;
      }
      .glow-btn:hover::after { opacity: 1; }

      .insight-item {
        position: relative;
        padding-left: 20px;
        margin-bottom: 12px;
        line-height: 1.6;
      }
      .insight-item::before {
        content: '→';
        position: absolute;
        left: 0;
        color: ${fgMuted};
      }
    `;
    document.head.appendChild(style);

    const obs = new IntersectionObserver(
      entries => entries.forEach(e => { if (e.isIntersecting) e.target.classList.add("visible"); }),
      { threshold: 0.1 }
    );
    document.querySelectorAll(".fade-up").forEach(el => obs.observe(el));

    return () => {
      document.head.removeChild(style);
      obs.disconnect();
    };
  }, []);

  // Separate effect to handle IntersectionObserver for dynamic content
  useEffect(() => {
    const obs = new IntersectionObserver(
      entries => entries.forEach(e => { 
        if (e.isIntersecting) {
          e.target.classList.add("visible");
        }
      }),
      { threshold: 0.1 }
    );

    const observeElements = () => {
      document.querySelectorAll(".fade-up:not(.visible)").forEach(el => obs.observe(el));
    };

    observeElements();
    
    // Re-run whenever sessions or filter changes
    const timeout = setTimeout(observeElements, 300);
    return () => {
      obs.disconnect();
      clearTimeout(timeout);
    };
  }, [sessions, filter]);

  return (
    <div style={{ background: bg, color: fg, minHeight: "100vh", fontFamily: "'DM Sans', sans-serif", overflowX: "hidden", position: "relative" }}>
      <Noise />

      <main style={{ maxWidth: 900, margin: "0 auto", padding: "60px 24px 100px", position: "relative", zIndex: 1 }}>
        
        {/* ── HEADER ── */}
        <header className="fade-up" style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", marginBottom: 60, flexWrap: "wrap", gap: 24 }}>
          <div>
            <div style={{ display: "inline-flex", alignItems: "center", gap: 8, background: cardBg, border: `1px solid ${cardBorder}`, borderRadius: 999, padding: "6px 16px", fontSize: 12, fontWeight: 500, color: fgMuted, marginBottom: 20, letterSpacing: 0.5 }}>
              <History size={12} />
              FOCUS ANALYTICS
            </div>
            <h1 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: "clamp(40px, 6vw, 64px)", letterSpacing: -0.5, lineHeight: 1.1, margin: 0 }}>
              YOUR FOCUS <span style={{ WebkitTextStroke: `1px ${fg}`, color: "transparent" }}>HISTORY</span>
            </h1>
            <p style={{ color: fgMuted, fontSize: 16, maxWidth: 450, marginTop: 12, lineHeight: 1.5 }}>
              Review your cognitive performance over time and identify patterns in your daily workflow.
            </p>
          </div>

          {total > 0 && (
            <div style={{ display: "flex", gap: 12 }}>
              <button className="glow-btn" onClick={() => downloadAllCSV(sessions)} style={{ background: fg, color: bg, border: "none", borderRadius: 12, padding: "12px 24px", fontSize: 14, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", gap: 8 }}>
                <Download size={16} /> Export CSV
              </button>
              {confirmClear ? (
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <button onClick={handleClearAll} style={{ background: "#f87171", color: "#fff", border: "none", borderRadius: 12, padding: "12px 20px", fontSize: 13, fontWeight: 700, cursor: "pointer" }}>Confirm</button>
                  <button onClick={() => setConfirmClear(false)} style={{ background: "transparent", color: fg, border: `1px solid ${border}`, borderRadius: 12, padding: "12px 20px", fontSize: 13, fontWeight: 700, cursor: "pointer" }}>Cancel</button>
                </div>
              ) : (
                <button onClick={() => setConfirmClear(true)} style={{ background: "transparent", color: fgMuted, border: `1px solid ${border}`, borderRadius: 12, padding: "12px 20px", fontSize: 14, fontWeight: 700, cursor: "pointer" }}>
                  <Trash2 size={16} />
                </button>
              )}
            </div>
          )}
        </header>

        {/* ── OVERVIEW ── */}
        {total > 0 && (
          <div className="fade-up premium-card" style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", background: cardBg, border: `1px solid ${cardBorder}`, borderRadius: 24, padding: "32px 0", marginBottom: 60 }}>
            <OverviewStat num={total} label="TOTAL SESSIONS" />
            <OverviewStat num={`${avgAttn}%`} label="AVERAGE ATTENTION" />
            <OverviewStat num={best?.grade ?? '—'} label="PEAK PERFORMANCE" highlight />
          </div>
        )}

        {/* ── FILTERS ── */}
        {total > 0 && (
          <div className="fade-up" style={{ display: "flex", gap: 8, marginBottom: 32, overflowX: "auto", paddingBottom: 12 }}>
            {['all', 'Excellent', 'Good', 'Fair', 'Needs Improvement'].map(f => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                style={{
                  background: filter === f ? fg : cardBg,
                  color: filter === f ? bg : fg,
                  border: `1px solid ${filter === f ? "transparent" : border}`,
                  borderRadius: 12, padding: "10px 20px", fontSize: 13, fontWeight: 700,
                  cursor: "pointer", transition: "all 0.3s ease", whiteSpace: "nowrap"
                }}
              >
                {f === 'all' ? 'All Activity' : f}
              </button>
            ))}
          </div>
        )}

        {/* ── EMPTY STATE ── */}
        {total === 0 && (
          <div className="fade-up" style={{ textAlign: "center", padding: "100px 0" }}>
            <div style={{ background: cardBg, border: `1px solid ${cardBorder}`, borderRadius: "50%", width: 80, height: 80, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 24px" }}>
              <Inbox size={32} color={fgMuted} />
            </div>
            <h3 style={{ fontSize: 24, fontWeight: 700, marginBottom: 8 }}>Archived intelligence is empty</h3>
            <p style={{ color: fgMuted, maxWidth: 300, margin: "0 auto" }}>Head to Face Detection to start tracking your cognitive flow.</p>
          </div>
        )}

        {/* ── LIST ── */}
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          {filtered.map((s, idx) => (
            <SessionCard
              key={s.id} session={s} index={total - idx}
              expanded={selected === s.id}
              onToggle={() => setSelected(selected === s.id ? null : s.id)}
              onDelete={() => handleDelete(s.id)}
              onDownloadTxt={() => downloadText(s)}
              onDownloadJSON={() => downloadJSON(s)}
              fg={fg} fgMuted={fgMuted} border={border} cardBg={cardBg} cardBorder={cardBorder}
            />
          ))}
          {filtered.length === 0 && total > 0 && (
            <div style={{ textAlign: "center", padding: "60px 0", color: fgMuted }}>
              No sessions match this performance tier.
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

function OverviewStat({ num, label, highlight }) {
  const { dark } = useTheme();
  const highlightColor = dark ? "#fff" : "#000";
  const labelColor = dark ? "rgba(255,255,255,0.35)" : "rgba(0,0,0,0.35)";
  const borderColor = dark ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.05)";

  return (
    <div style={{ textAlign: "center", borderRight: `1px solid ${borderColor}`, padding: "0 24px" }}>
      <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 40, color: highlight ? highlightColor : "inherit", lineHeight: 1, marginBottom: 8 }}>{num}</div>
      <div style={{ fontSize: 10, fontWeight: 800, color: labelColor, letterSpacing: 1.5 }}>{label}</div>
    </div>
  );
}

function SessionCard({ session: s, index, expanded, onToggle, onDelete, onDownloadTxt, onDownloadJSON, fg, fgMuted, border, cardBg, cardBorder }) {
  return (
    <div className="fade-up premium-card" style={{ 
      background: cardBg, border: `1px solid ${expanded ? fg : cardBorder}`, 
      borderRadius: 20, overflow: "hidden"
    }}>
      <div style={{ padding: 24, cursor: "pointer" }} onClick={onToggle}>
        <div style={{ display: "flex", alignItems: "center", gap: 20, flexWrap: "wrap" }}>
          
          {/* Grade Badge */}
          <div style={{ background: fg, color: "black", padding: "12px 16px", borderRadius: 12, minWidth: 80, textAlign: "center" }}>
            <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, lineHeight: 1 }}>{s.grade === 'Needs Improvement' ? 'NI' : s.grade.toUpperCase()}</div>
          </div>

          <div style={{ flex: 1 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 12, fontWeight: 600, color: fgMuted, marginBottom: 4 }}>
              <Calendar size={12} /> {fmtDate(s.startTimeISO)}
              <span style={{ opacity: 0.3 }}>•</span>
              <span>SESSION #{index}</span>
            </div>
            <div style={{ fontSize: 15, fontWeight: 500, color: fg }}>{sessionSummary(s)}</div>
          </div>

          <div style={{ display: "flex", gap: 24 }}>
            <QuickStat icon={<Clock size={14} />} value={s.totalDuration} fgMuted={fgMuted} />
            <QuickStat icon={<Eye size={14} />} value={`${s.attentionPercent}%`} fgMuted={fgMuted} highlight />
            <QuickStat icon={<Shuffle size={14} />} value={s.tabSwitches} fgMuted={fgMuted} />
            <div style={{ color: fgMuted }}>
              {expanded ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
            </div>
          </div>
        </div>
      </div>

      {expanded && (
        <div style={{ padding: "0 24px 32px" }}>
          <div style={{ height: 1, background: border, marginBottom: 32 }} />
          
          {/* ── SESSION INTELLIGENCE HEADER ── */}
          <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 32 }}>
            <h2 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 32, margin: 0 }}>SESSION <span style={{ color: fgMuted }}>INTELLIGENCE</span></h2>
            <div style={{ height: 1, flex: 1, background: border }} />
          </div>

          {/* Grade Summary Section */}
          <div style={{ 
            display: 'flex', alignItems: 'center', gap: '1.5rem', 
            backgroundColor: dark ? "rgba(255,255,255,0.02)" : "rgba(0,0,0,0.02)", 
            borderRadius: '16px', padding: '24px 32px', 
            marginBottom: '32px', border: `1px solid ${cardBorder}` 
          }}>
            <GradeIcon grade={s.grade} size={40} />
            <div>
              <div style={{ color: fg, fontWeight: 800, fontSize: '1.8rem', letterSpacing: '-0.5px', fontFamily: "'Bebas Neue', sans-serif", lineHeight: 1 }}>{s.grade.toUpperCase()}</div>
              <div style={{ color: fgMuted, fontSize: '14px', fontWeight: 500 }}>Overall attention rating for this session</div>
            </div>
          </div>

          {/* Full Metrics Grid */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: 16, marginBottom: 40 }}>
            <MetricCard label="Start Time"     value={s.startTime} />
            <MetricCard label="End Time"       value={s.endTime} />
            <MetricCard label="Total Duration" value={s.totalDuration} />
            <MetricCard label="Focused Time"   value={s.focusedTime} />
            <MetricCard label="Away Time"      value={s.awayTime} />
            <MetricCard label="Attention"      value={`${s.attentionPercent}%`} highlight />
            <MetricCard label="No-Face Alerts" value={s.noFaceAlerts} />
            <MetricCard label="Distractions"   value={s.tabSwitches} />
          </div>

          {/* Attention Bar */}
          <div style={{ marginBottom: '40px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
              <span style={{ color: fgMuted, fontSize: '12px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '1px' }}>Attention Score</span>
              <span style={{ color: fg, fontWeight: 800, fontSize: '14px' }}>{s.attentionPercent}%</span>
            </div>
            <div style={{ height: 6, background: border, borderRadius: 3, overflow: 'hidden' }}>
              <div style={{ height: "100%", width: `${s.attentionPercent}%`, background: fg, borderRadius: 3 }} />
            </div>
          </div>

          {/* Distraction Log (Timeline) */}
          {(s.awayEvents || []).length > 0 && (
            <div className="premium-card" style={{ 
              background: dark ? "rgba(255,255,255,0.02)" : "rgba(0,0,0,0.02)", 
              border: `1px solid ${border}`, 
              borderRadius: 24, padding: 32, marginBottom: 32
            }}>
              <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, marginBottom: 24 }}>DISTRACTION LOG</h3>
              <div style={{ display: "flex", flexDirection: "column", gap: 1 }}>
                {s.awayEvents.map((ev, i) => (
                  <div key={i} style={{ 
                    display: "grid", gridTemplateColumns: "100px 1fr 150px 100px", gap: 20,
                    padding: "16px 0", borderBottom: i === s.awayEvents.length - 1 ? "none" : `1px solid ${border}`,
                    alignItems: "center"
                  }}>
                    <div style={{ fontSize: 12, fontWeight: 700, color: fgMuted }}>{new Date(ev.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</div>
                    <div style={{ fontSize: 14, fontWeight: 500 }}>{ev.label}</div>
                    <div style={{ fontSize: 12, color: fgMuted, display: "flex", alignItems: "center", gap: 6 }}>
                      <span style={{ background: border, padding: "2px 8px", borderRadius: 4, fontSize: 10 }}>{ev.kind.toUpperCase()}</span>
                      {ev.endTime ? `to ${new Date(ev.endTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}` : ""}
                    </div>
                    <div style={{ fontSize: 14, fontWeight: 700, textAlign: "right" }}>{elapsed(ev.durationMs)}</div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Insights */}
          <div className="premium-card" style={{ background: dark ? "rgba(255,255,255,0.02)" : "rgba(0,0,0,0.02)", border: `1px solid ${border}`, borderRadius: 24, padding: 32, marginBottom: 48 }}>
            <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, marginBottom: 20 }}>INSIGHTS</h3>
            <div style={{ color: fgMuted, fontSize: 14, lineHeight: 1.8 }}>
              {s.attentionPercent >= 85 && <div className="insight-item" style={{ color: fg }}>Great focus — you maintained strong attention throughout the session.</div>}
              {s.attentionPercent < 85 && s.attentionPercent >= 65 && <div className="insight-item">Good session. A few attention dips — try minimizing distractions.</div>}
              {s.attentionPercent < 65 && <div className="insight-item">Attention was low. Consider shorter sessions with breaks.</div>}
              {s.tabSwitches === 0 && <div className="insight-item" style={{ color: fg }}>Zero distractions — excellent focus environment!</div>}
              {s.tabSwitches > 0 && s.tabSwitches <= 3 && <div className="insight-item">Minimal distractions ({s.tabSwitches}) — good discipline.</div>}
              {s.tabSwitches > 3 && <div className="insight-item">You left the session {s.tabSwitches} times — try closing other apps before starting.</div>}
              {(s.awayEvents || []).some(e => e.durationMs > 60000) && <div className="insight-item">At least one distraction lasted over a minute — consider using Do Not Disturb mode.</div>}
              {s.noFaceAlerts > 3 && <div className="insight-item">Multiple no-face alerts — make sure you're seated in front of the camera.</div>}
            </div>
          </div>

          {/* Actions */}
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap", borderTop: `1px solid ${border}`, paddingTop: 32 }}>
            <button onClick={onDownloadTxt} style={{ background: fg, color: bg, border: "none", borderRadius: 12, padding: "12px 24px", fontSize: 14, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", gap: 8 }}>
              <FileText size={16} /> Download Report
            </button>
            <button onClick={onDownloadJSON} style={{ background: "transparent", color: fg, border: `1px solid ${border}`, borderRadius: 12, padding: "12px 24px", fontSize: 14, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", gap: 8 }}>
              <FileJson size={16} /> JSON
            </button>
            <button onClick={onDelete} style={{ marginLeft: "auto", background: "transparent", color: "#f87171", border: `1px solid rgba(248,113,113,0.2)`, borderRadius: 12, padding: "12px 24px", fontSize: 14, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", gap: 8 }}>
              <Trash2 size={16} /> Delete
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function QuickStat({ icon, value, fgMuted, highlight }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13, fontWeight: 700, color: highlight ? "inherit" : fgMuted }}>
      {icon} {value}
    </div>
  );
}

function MetricCard({ label, value, highlight = false }) {
  const { dark } = useTheme();
  const cardBg = dark ? "rgba(255,255,255,0.03)" : "rgba(0,0,0,0.03)";
  const cardBorder = dark ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.08)";
  const labelColor = dark ? "rgba(255,255,255,0.35)" : "rgba(0,0,0,0.35)";
  const valueColor = dark ? (highlight ? "#fff" : "rgba(255,255,255,0.85)") : (highlight ? "#000" : "rgba(0,0,0,0.85)");

  return (
    <div style={{ 
      background: cardBg, border: `1px solid ${cardBorder}`, 
      borderRadius: '12px', padding: '16px', display: 'flex', flexDirection: 'column', gap: '4px'
    }}>
      <div style={{ fontSize: '10px', fontWeight: 700, color: labelColor, textTransform: 'uppercase', letterSpacing: '0.8px' }}>{label}</div>
      <div style={{ fontSize: '18px', fontWeight: 700, color: valueColor }}>{value}</div>
    </div>
  );
}

function PillStat({ icon, label, value, fg, fgMuted, border }) {
  const { dark } = useTheme();
  const labelColor = dark ? "rgba(255,255,255,0.35)" : "rgba(0,0,0,0.35)";
  const bgColor = dark ? "rgba(255,255,255,0.02)" : "rgba(0,0,0,0.02)";

  return (
    <div style={{ background: bgColor, border: `1px solid ${border}`, borderRadius: 12, padding: 16 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 6, color: labelColor, fontSize: 10, fontWeight: 800, letterSpacing: 0.5, marginBottom: 4 }}>
        {icon} {label}
      </div>
      <div style={{ fontSize: 18, fontWeight: 700, color: fg }}>{value}</div>
    </div>
  );
}

function GradeIcon({ grade, size = 24 }) {
  const { dark } = useTheme();
  const color = dark ? "#000" : "#fff";
  if (grade === 'Excellent') return <Trophy size={size} color={color} />;
  if (grade === 'Good')      return <ThumbsUp size={size} color={color} />;
  if (grade === 'Fair')      return <TrendingUp size={size} color={color} />;
  return <AlertTriangle size={size} color={color} />;
}
